### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by ghazanfarabbas** [SAP-archive/s4hana-ext-cloud-label-printing#3]
Hi 

I am trying to test the print label app but getting the 404 not found error:

Please check the manifest.yml as well. Any idea what I am missing?

approuter URL(trying to access the app with the URL): https://mytest.cfapps.eu10.hana.ondemand.com/printlabel

**manifest.json**
{
	"_version": "1.12.0",
	"sap.app": {
		"id": "printlabel",
                  .....
}
**manifest.yml**
{
---
applications:

- name: approuter
  routes:
   # TODO replace a placeholder with the value of your choice
  - route: https://mytest.cfapps.eu10.hana.ondemand.com
  path: approuter
  memory: 128M
  buildpacks:
  - nodejs_buildpack
  env:
    # TODO replace placeholders with the previously chosen routes
    destinations: '[
      {"name": "backend", "url": "https://mytest.cfapps.eu10.hana.ondemand.com/printlabelbackend", "forwardAuthToken": true},
      {"name": "frontend", "url": "https://mytest.cfapps.eu10.hana.ondemand.com/printlabelfrontend"}
    ]'
  services:
  # TODO replace placeholder with the name of the same instance that is used by the backend application
  - psrvauth

- name: backend
  memory: 1024M
  timeout: 300
  routes:
   # TODO replace a placeholder with the value of your choice
  - route: https://mytest.cfapps.eu10.hana.ondemand.com/printlabelbackend 
  path: srv/target/print-application.war
  buildpacks:
  - sap_java_buildpack
  env:
    TARGET_RUNTIME: tomee7
    SET_LOGGING_LEVEL: '{ROOT: INFO, com.sap.cloud.sdk: INFO}'
    JBP_CONFIG_SAPJVM_MEMORY_SIZES: 'metaspace:128m..'
  services:
  # TODO replace placeholders with the existing service instances names
  - psrvauth
  - psrvsender
  - psrvreceiver
    
- name: frontend
  routes:
  # TODO replace a placeholder with the value of your choice
  - route: https://mytest.cfapps.eu10.hana.ondemand.com/printlabelfrontend
  path: frontend/webapp
  root: WebContent
  memory: 64M
  disk_quota: 128M
  buildpacks: 
  - staticfile_buildpack
}

**Comment by JTR7** [comment]
Is there anyone supporting this scenario? I've also came across the same issue 404 Not Found. Thought it was related to deprecated UI5 library versions. I've changed them but still experiencing the same issue.

**Comment by charlottehu111** [comment]
Yes, the reason is that UI5 is out of date. Currently we are going to release the updated UI5 version in this month. This version works fine.
